/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tk.hildebrandt.tdd.bowling;

public class BowlingGame {

   public void roll(int pins) {
   }

   public int score() {
      return -1;
   }
}
